# Generated by Django 4.1.2 on 2022-10-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True, unique=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Phone_Number', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Role', models.CharField(max_length=30, null=True, unique=True)),
                ('Created_by', models.BooleanField(blank=True, default=True, null=True)),
                ('Created_at', models.BooleanField()),
                ('Last_Updated_at', models.BooleanField()),
                ('Department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerXPAPI.department')),
            ],
        ),
    ]
