# Generated by Django 4.1.2 on 2022-10-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peerXPAPI', '0002_newdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTickect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=30, null=True, unique=True)),
                ('Body', models.TextField()),
                ('Priority', models.PositiveSmallIntegerField()),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Phone_Number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageTicket',
            fields=[
                ('Ticket_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Priority', models.PositiveSmallIntegerField(unique=True, verbose_name='priority')),
                ('Created_at', models.BooleanField()),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peerXPAPI.newtickect')),
            ],
        ),
    ]
